/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbCompany extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_company.id</code>.
     */
    public ITbCompany setId(Long value);

    /**
     * Getter for <code>public.tb_company.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_company.name</code>.
     */
    public ITbCompany setName(String value);

    /**
     * Getter for <code>public.tb_company.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_company.location</code>.
     */
    public ITbCompany setLocation(String value);

    /**
     * Getter for <code>public.tb_company.location</code>.
     */
    public String getLocation();

    /**
     * Setter for <code>public.tb_company.phone_number</code>.
     */
    public ITbCompany setPhoneNumber(String value);

    /**
     * Getter for <code>public.tb_company.phone_number</code>.
     */
    public String getPhoneNumber();

    /**
     * Setter for <code>public.tb_company.sector</code>.
     */
    public ITbCompany setSector(String value);

    /**
     * Getter for <code>public.tb_company.sector</code>.
     */
    public String getSector();

    /**
     * Setter for <code>public.tb_company.rating</code>.
     */
    public ITbCompany setRating(Integer value);

    /**
     * Getter for <code>public.tb_company.rating</code>.
     */
    public Integer getRating();

    /**
     * Setter for <code>public.tb_company.logo</code>.
     */
    public ITbCompany setLogo(String value);

    /**
     * Getter for <code>public.tb_company.logo</code>.
     */
    public String getLogo();

    /**
     * Setter for <code>public.tb_company.background_info</code>.
     */
    public ITbCompany setBackgroundInfo(String value);

    /**
     * Getter for <code>public.tb_company.background_info</code>.
     */
    public String getBackgroundInfo();

    /**
     * Setter for <code>public.tb_company.entities</code>.
     */
    public ITbCompany setEntities(String value);

    /**
     * Getter for <code>public.tb_company.entities</code>.
     */
    public String getEntities();

    /**
     * Setter for <code>public.tb_company.company_id</code>.
     */
    public ITbCompany setCompanyId(String value);

    /**
     * Getter for <code>public.tb_company.company_id</code>.
     */
    public String getCompanyId();

    /**
     * Setter for <code>public.tb_company.company_code</code>.
     */
    public ITbCompany setCompanyCode(String value);

    /**
     * Getter for <code>public.tb_company.company_code</code>.
     */
    public String getCompanyCode();

    /**
     * Setter for <code>public.tb_company.created_at</code>.
     */
    public ITbCompany setCreatedAt(OffsetTime value);

    /**
     * Getter for <code>public.tb_company.created_at</code>.
     */
    public OffsetTime getCreatedAt();

    /**
     * Setter for <code>public.tb_company.created_by</code>.
     */
    public ITbCompany setCreatedBy(String value);

    /**
     * Getter for <code>public.tb_company.created_by</code>.
     */
    public String getCreatedBy();

    /**
     * Setter for <code>public.tb_company.email</code>.
     */
    public ITbCompany setEmail(String value);

    /**
     * Getter for <code>public.tb_company.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.tb_company.website</code>.
     */
    public ITbCompany setWebsite(String value);

    /**
     * Getter for <code>public.tb_company.website</code>.
     */
    public String getWebsite();

    /**
     * Setter for <code>public.tb_company.other_links</code>.
     */
    public ITbCompany setOtherLinks(String value);

    /**
     * Getter for <code>public.tb_company.other_links</code>.
     */
    public String getOtherLinks();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbCompany
     */
    public void from(jooq.tables.interfaces.ITbCompany from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbCompany
     */
    public <E extends jooq.tables.interfaces.ITbCompany> E into(E into);

    @Override
    public default ITbCompany fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setLocation(json.getString("location"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("location","java.lang.String",e);
        }
        try {
            setPhoneNumber(json.getString("phone_number"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("phone_number","java.lang.String",e);
        }
        try {
            setSector(json.getString("sector"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sector","java.lang.String",e);
        }
        try {
            setRating(json.getInteger("rating"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("rating","java.lang.Integer",e);
        }
        try {
            setLogo(json.getString("logo"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("logo","java.lang.String",e);
        }
        try {
            setBackgroundInfo(json.getString("background_info"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("background_info","java.lang.String",e);
        }
        try {
            setEntities(json.getString("entities"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("entities","java.lang.String",e);
        }
        try {
            setCompanyId(json.getString("company_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("company_id","java.lang.String",e);
        }
        try {
            setCompanyCode(json.getString("company_code"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("company_code","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.OffsetTime for column created_at!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_at","java.time.OffsetTime",e);
        }
        try {
            setCreatedBy(json.getString("created_by"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_by","java.lang.String",e);
        }
        try {
            setEmail(json.getString("email"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("email","java.lang.String",e);
        }
        try {
            setWebsite(json.getString("website"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("website","java.lang.String",e);
        }
        try {
            setOtherLinks(json.getString("other_links"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("other_links","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("name",getName());
        json.put("location",getLocation());
        json.put("phone_number",getPhoneNumber());
        json.put("sector",getSector());
        json.put("rating",getRating());
        json.put("logo",getLogo());
        json.put("background_info",getBackgroundInfo());
        json.put("entities",getEntities());
        json.put("company_id",getCompanyId());
        json.put("company_code",getCompanyCode());
        // Omitting unrecognized type java.time.OffsetTime for column created_at!
        json.put("created_by",getCreatedBy());
        json.put("email",getEmail());
        json.put("website",getWebsite());
        json.put("other_links",getOtherLinks());
        return json;
    }

}
