/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbCategory extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_category.id</code>.
     */
    public ITbCategory setId(Long value);

    /**
     * Getter for <code>public.tb_category.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_category.cid</code>.
     */
    public ITbCategory setCid(String value);

    /**
     * Getter for <code>public.tb_category.cid</code>.
     */
    public String getCid();

    /**
     * Setter for <code>public.tb_category.name</code>.
     */
    public ITbCategory setName(String value);

    /**
     * Getter for <code>public.tb_category.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_category.description</code>.
     */
    public ITbCategory setDescription(String value);

    /**
     * Getter for <code>public.tb_category.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.tb_category.created_by</code>.
     */
    public ITbCategory setCreatedBy(String value);

    /**
     * Getter for <code>public.tb_category.created_by</code>.
     */
    public String getCreatedBy();

    /**
     * Setter for <code>public.tb_category.created_at</code>.
     */
    public ITbCategory setCreatedAt(OffsetTime value);

    /**
     * Getter for <code>public.tb_category.created_at</code>.
     */
    public OffsetTime getCreatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbCategory
     */
    public void from(jooq.tables.interfaces.ITbCategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbCategory
     */
    public <E extends jooq.tables.interfaces.ITbCategory> E into(E into);

    @Override
    public default ITbCategory fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setCid(json.getString("cid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("cid","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setDescription(json.getString("description"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("description","java.lang.String",e);
        }
        try {
            setCreatedBy(json.getString("created_by"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_by","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.OffsetTime for column created_at!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_at","java.time.OffsetTime",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("cid",getCid());
        json.put("name",getName());
        json.put("description",getDescription());
        json.put("created_by",getCreatedBy());
        // Omitting unrecognized type java.time.OffsetTime for column created_at!
        return json;
    }

}
