/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbInterest extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_interest.id</code>.
     */
    public ITbInterest setId(Long value);

    /**
     * Getter for <code>public.tb_interest.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_interest.iid</code>.
     */
    public ITbInterest setIid(String value);

    /**
     * Getter for <code>public.tb_interest.iid</code>.
     */
    public String getIid();

    /**
     * Setter for <code>public.tb_interest.description</code>.
     */
    public ITbInterest setDescription(String value);

    /**
     * Getter for <code>public.tb_interest.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.tb_interest.name</code>.
     */
    public ITbInterest setName(String value);

    /**
     * Getter for <code>public.tb_interest.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_interest.createdby</code>.
     */
    public ITbInterest setCreatedby(String value);

    /**
     * Getter for <code>public.tb_interest.createdby</code>.
     */
    public String getCreatedby();

    /**
     * Setter for <code>public.tb_interest.createdon</code>.
     */
    public ITbInterest setCreatedon(Timestamp value);

    /**
     * Getter for <code>public.tb_interest.createdon</code>.
     */
    public Timestamp getCreatedon();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbInterest
     */
    public void from(jooq.tables.interfaces.ITbInterest from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbInterest
     */
    public <E extends jooq.tables.interfaces.ITbInterest> E into(E into);

    @Override
    public default ITbInterest fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setIid(json.getString("iid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("iid","java.lang.String",e);
        }
        try {
            setDescription(json.getString("description"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("description","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setCreatedby(json.getString("createdby"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdby","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.sql.Timestamp for column createdon!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdon","java.sql.Timestamp",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("iid",getIid());
        json.put("description",getDescription());
        json.put("name",getName());
        json.put("createdby",getCreatedby());
        // Omitting unrecognized type java.sql.Timestamp for column createdon!
        return json;
    }

}
