/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbLikes extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_likes.id</code>.
     */
    public ITbLikes setId(Long value);

    /**
     * Getter for <code>public.tb_likes.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_likes.authorid</code>.
     */
    public ITbLikes setAuthorid(String value);

    /**
     * Getter for <code>public.tb_likes.authorid</code>.
     */
    public String getAuthorid();

    /**
     * Setter for <code>public.tb_likes.lid</code>.
     */
    public ITbLikes setLid(String value);

    /**
     * Getter for <code>public.tb_likes.lid</code>.
     */
    public String getLid();

    /**
     * Setter for <code>public.tb_likes.comment_id</code>.
     */
    public ITbLikes setCommentId(String value);

    /**
     * Getter for <code>public.tb_likes.comment_id</code>.
     */
    public String getCommentId();

    /**
     * Setter for <code>public.tb_likes.storyid</code>.
     */
    public ITbLikes setStoryid(String value);

    /**
     * Getter for <code>public.tb_likes.storyid</code>.
     */
    public String getStoryid();

    /**
     * Setter for <code>public.tb_likes.possibilitysensitive</code>.
     */
    public ITbLikes setPossibilitysensitive(Integer value);

    /**
     * Getter for <code>public.tb_likes.possibilitysensitive</code>.
     */
    public Integer getPossibilitysensitive();

    /**
     * Setter for <code>public.tb_likes.lang</code>.
     */
    public ITbLikes setLang(String value);

    /**
     * Getter for <code>public.tb_likes.lang</code>.
     */
    public String getLang();

    /**
     * Setter for <code>public.tb_likes.entities</code>.
     */
    public ITbLikes setEntities(String value);

    /**
     * Getter for <code>public.tb_likes.entities</code>.
     */
    public String getEntities();

    /**
     * Setter for <code>public.tb_likes.authorname</code>.
     */
    public ITbLikes setAuthorname(String value);

    /**
     * Getter for <code>public.tb_likes.authorname</code>.
     */
    public String getAuthorname();

    /**
     * Setter for <code>public.tb_likes.createdon</code>.
     */
    public ITbLikes setCreatedon(String value);

    /**
     * Getter for <code>public.tb_likes.createdon</code>.
     */
    public String getCreatedon();

    /**
     * Setter for <code>public.tb_likes.status</code>.
     */
    public ITbLikes setStatus(String value);

    /**
     * Getter for <code>public.tb_likes.status</code>.
     */
    public String getStatus();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbLikes
     */
    public void from(jooq.tables.interfaces.ITbLikes from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbLikes
     */
    public <E extends jooq.tables.interfaces.ITbLikes> E into(E into);

    @Override
    public default ITbLikes fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setAuthorid(json.getString("authorid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("authorid","java.lang.String",e);
        }
        try {
            setLid(json.getString("lid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("lid","java.lang.String",e);
        }
        try {
            setCommentId(json.getString("comment_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("comment_id","java.lang.String",e);
        }
        try {
            setStoryid(json.getString("storyid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("storyid","java.lang.String",e);
        }
        try {
            setPossibilitysensitive(json.getInteger("possibilitysensitive"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("possibilitysensitive","java.lang.Integer",e);
        }
        try {
            setLang(json.getString("lang"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("lang","java.lang.String",e);
        }
        try {
            setEntities(json.getString("entities"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("entities","java.lang.String",e);
        }
        try {
            setAuthorname(json.getString("authorname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("authorname","java.lang.String",e);
        }
        try {
            setCreatedon(json.getString("createdon"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdon","java.lang.String",e);
        }
        try {
            setStatus(json.getString("status"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("status","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("authorid",getAuthorid());
        json.put("lid",getLid());
        json.put("comment_id",getCommentId());
        json.put("storyid",getStoryid());
        json.put("possibilitysensitive",getPossibilitysensitive());
        json.put("lang",getLang());
        json.put("entities",getEntities());
        json.put("authorname",getAuthorname());
        json.put("createdon",getCreatedon());
        json.put("status",getStatus());
        return json;
    }

}
