/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbStory extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_story.id</code>.
     */
    public ITbStory setId(Long value);

    /**
     * Getter for <code>public.tb_story.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_story.authorid</code>.
     */
    public ITbStory setAuthorid(String value);

    /**
     * Getter for <code>public.tb_story.authorid</code>.
     */
    public String getAuthorid();

    /**
     * Setter for <code>public.tb_story.entities</code>.
     */
    public ITbStory setEntities(String value);

    /**
     * Getter for <code>public.tb_story.entities</code>.
     */
    public String getEntities();

    /**
     * Setter for <code>public.tb_story.sid</code>.
     */
    public ITbStory setSid(String value);

    /**
     * Getter for <code>public.tb_story.sid</code>.
     */
    public String getSid();

    /**
     * Setter for <code>public.tb_story.lang</code>.
     */
    public ITbStory setLang(String value);

    /**
     * Getter for <code>public.tb_story.lang</code>.
     */
    public String getLang();

    /**
     * Setter for <code>public.tb_story.possiblysensitive</code>.
     */
    public ITbStory setPossiblysensitive(Integer value);

    /**
     * Getter for <code>public.tb_story.possiblysensitive</code>.
     */
    public Integer getPossiblysensitive();

    /**
     * Setter for <code>public.tb_story.source</code>.
     */
    public ITbStory setSource(String value);

    /**
     * Getter for <code>public.tb_story.source</code>.
     */
    public String getSource();

    /**
     * Setter for <code>public.tb_story.story</code>.
     */
    public ITbStory setStory(String value);

    /**
     * Getter for <code>public.tb_story.story</code>.
     */
    public String getStory();

    /**
     * Setter for <code>public.tb_story.likecount</code>.
     */
    public ITbStory setLikecount(Integer value);

    /**
     * Getter for <code>public.tb_story.likecount</code>.
     */
    public Integer getLikecount();

    /**
     * Setter for <code>public.tb_story.commentcount</code>.
     */
    public ITbStory setCommentcount(Integer value);

    /**
     * Getter for <code>public.tb_story.commentcount</code>.
     */
    public Integer getCommentcount();

    /**
     * Setter for <code>public.tb_story.cautioncount</code>.
     */
    public ITbStory setCautioncount(Integer value);

    /**
     * Getter for <code>public.tb_story.cautioncount</code>.
     */
    public Integer getCautioncount();

    /**
     * Setter for <code>public.tb_story.categoryname</code>.
     */
    public ITbStory setCategoryname(String value);

    /**
     * Getter for <code>public.tb_story.categoryname</code>.
     */
    public String getCategoryname();

    /**
     * Setter for <code>public.tb_story.sectorname</code>.
     */
    public ITbStory setSectorname(String value);

    /**
     * Getter for <code>public.tb_story.sectorname</code>.
     */
    public String getSectorname();

    /**
     * Setter for <code>public.tb_story.companyid</code>.
     */
    public ITbStory setCompanyid(String value);

    /**
     * Getter for <code>public.tb_story.companyid</code>.
     */
    public String getCompanyid();

    /**
     * Setter for <code>public.tb_story.sectorid</code>.
     */
    public ITbStory setSectorid(String value);

    /**
     * Getter for <code>public.tb_story.sectorid</code>.
     */
    public String getSectorid();

    /**
     * Setter for <code>public.tb_story.categoryid</code>.
     */
    public ITbStory setCategoryid(String value);

    /**
     * Getter for <code>public.tb_story.categoryid</code>.
     */
    public String getCategoryid();

    /**
     * Setter for <code>public.tb_story.authorname</code>.
     */
    public ITbStory setAuthorname(String value);

    /**
     * Getter for <code>public.tb_story.authorname</code>.
     */
    public String getAuthorname();

    /**
     * Setter for <code>public.tb_story.companyname</code>.
     */
    public ITbStory setCompanyname(String value);

    /**
     * Getter for <code>public.tb_story.companyname</code>.
     */
    public String getCompanyname();

    /**
     * Setter for <code>public.tb_story.createdon</code>.
     */
    public ITbStory setCreatedon(String value);

    /**
     * Getter for <code>public.tb_story.createdon</code>.
     */
    public String getCreatedon();

    /**
     * Setter for <code>public.tb_story.gpslocation</code>.
     */
    public ITbStory setGpslocation(String value);

    /**
     * Getter for <code>public.tb_story.gpslocation</code>.
     */
    public String getGpslocation();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbStory
     */
    public void from(jooq.tables.interfaces.ITbStory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbStory
     */
    public <E extends jooq.tables.interfaces.ITbStory> E into(E into);

    @Override
    public default ITbStory fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setAuthorid(json.getString("authorid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("authorid","java.lang.String",e);
        }
        try {
            setEntities(json.getString("entities"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("entities","java.lang.String",e);
        }
        try {
            setSid(json.getString("sid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sid","java.lang.String",e);
        }
        try {
            setLang(json.getString("lang"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("lang","java.lang.String",e);
        }
        try {
            setPossiblysensitive(json.getInteger("possiblysensitive"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("possiblysensitive","java.lang.Integer",e);
        }
        try {
            setSource(json.getString("source"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("source","java.lang.String",e);
        }
        try {
            setStory(json.getString("story"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("story","java.lang.String",e);
        }
        try {
            setLikecount(json.getInteger("likecount"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("likecount","java.lang.Integer",e);
        }
        try {
            setCommentcount(json.getInteger("commentcount"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("commentcount","java.lang.Integer",e);
        }
        try {
            setCautioncount(json.getInteger("cautioncount"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("cautioncount","java.lang.Integer",e);
        }
        try {
            setCategoryname(json.getString("categoryname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("categoryname","java.lang.String",e);
        }
        try {
            setSectorname(json.getString("sectorname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sectorname","java.lang.String",e);
        }
        try {
            setCompanyid(json.getString("companyid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("companyid","java.lang.String",e);
        }
        try {
            setSectorid(json.getString("sectorid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sectorid","java.lang.String",e);
        }
        try {
            setCategoryid(json.getString("categoryid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("categoryid","java.lang.String",e);
        }
        try {
            setAuthorname(json.getString("authorname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("authorname","java.lang.String",e);
        }
        try {
            setCompanyname(json.getString("companyname"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("companyname","java.lang.String",e);
        }
        try {
            setCreatedon(json.getString("createdon"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdon","java.lang.String",e);
        }
        try {
            setGpslocation(json.getString("gpslocation"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("gpslocation","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("authorid",getAuthorid());
        json.put("entities",getEntities());
        json.put("sid",getSid());
        json.put("lang",getLang());
        json.put("possiblysensitive",getPossiblysensitive());
        json.put("source",getSource());
        json.put("story",getStory());
        json.put("likecount",getLikecount());
        json.put("commentcount",getCommentcount());
        json.put("cautioncount",getCautioncount());
        json.put("categoryname",getCategoryname());
        json.put("sectorname",getSectorname());
        json.put("companyid",getCompanyid());
        json.put("sectorid",getSectorid());
        json.put("categoryid",getCategoryid());
        json.put("authorname",getAuthorname());
        json.put("companyname",getCompanyname());
        json.put("createdon",getCreatedon());
        json.put("gpslocation",getGpslocation());
        return json;
    }

}
