/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbSector extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_sector.id</code>.
     */
    public ITbSector setId(Long value);

    /**
     * Getter for <code>public.tb_sector.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_sector.sid</code>.
     */
    public ITbSector setSid(String value);

    /**
     * Getter for <code>public.tb_sector.sid</code>.
     */
    public String getSid();

    /**
     * Setter for <code>public.tb_sector.name</code>.
     */
    public ITbSector setName(String value);

    /**
     * Getter for <code>public.tb_sector.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_sector.createdby</code>.
     */
    public ITbSector setCreatedby(String value);

    /**
     * Getter for <code>public.tb_sector.createdby</code>.
     */
    public String getCreatedby();

    /**
     * Setter for <code>public.tb_sector.description</code>.
     */
    public ITbSector setDescription(String value);

    /**
     * Getter for <code>public.tb_sector.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.tb_sector.createdon</code>.
     */
    public ITbSector setCreatedon(String value);

    /**
     * Getter for <code>public.tb_sector.createdon</code>.
     */
    public String getCreatedon();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbSector
     */
    public void from(jooq.tables.interfaces.ITbSector from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbSector
     */
    public <E extends jooq.tables.interfaces.ITbSector> E into(E into);

    @Override
    public default ITbSector fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setSid(json.getString("sid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sid","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setCreatedby(json.getString("createdby"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdby","java.lang.String",e);
        }
        try {
            setDescription(json.getString("description"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("description","java.lang.String",e);
        }
        try {
            setCreatedon(json.getString("createdon"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("createdon","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("sid",getSid());
        json.put("name",getName());
        json.put("createdby",getCreatedby());
        json.put("description",getDescription());
        json.put("createdon",getCreatedon());
        return json;
    }

}
