/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbUser extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_user.id</code>.
     */
    public ITbUser setId(Long value);

    /**
     * Getter for <code>public.tb_user.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_user.role_id</code>.
     */
    public ITbUser setRoleId(String value);

    /**
     * Getter for <code>public.tb_user.role_id</code>.
     */
    public String getRoleId();

    /**
     * Setter for <code>public.tb_user.first_name</code>.
     */
    public ITbUser setFirstName(String value);

    /**
     * Getter for <code>public.tb_user.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>public.tb_user.last_name</code>.
     */
    public ITbUser setLastName(String value);

    /**
     * Getter for <code>public.tb_user.last_name</code>.
     */
    public String getLastName();

    /**
     * Setter for <code>public.tb_user.email</code>.
     */
    public ITbUser setEmail(String value);

    /**
     * Getter for <code>public.tb_user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.tb_user.mobile</code>.
     */
    public ITbUser setMobile(String value);

    /**
     * Getter for <code>public.tb_user.mobile</code>.
     */
    public String getMobile();

    /**
     * Setter for <code>public.tb_user.hashed_password</code>.
     */
    public ITbUser setHashedPassword(String value);

    /**
     * Getter for <code>public.tb_user.hashed_password</code>.
     */
    public String getHashedPassword();

    /**
     * Setter for <code>public.tb_user.salt</code>.
     */
    public ITbUser setSalt(String value);

    /**
     * Getter for <code>public.tb_user.salt</code>.
     */
    public String getSalt();

    /**
     * Setter for <code>public.tb_user.profile_pic</code>.
     */
    public ITbUser setProfilePic(String value);

    /**
     * Getter for <code>public.tb_user.profile_pic</code>.
     */
    public String getProfilePic();

    /**
     * Setter for <code>public.tb_user.background_info</code>.
     */
    public ITbUser setBackgroundInfo(String value);

    /**
     * Getter for <code>public.tb_user.background_info</code>.
     */
    public String getBackgroundInfo();

    /**
     * Setter for <code>public.tb_user.website</code>.
     */
    public ITbUser setWebsite(String value);

    /**
     * Getter for <code>public.tb_user.website</code>.
     */
    public String getWebsite();

    /**
     * Setter for <code>public.tb_user.gps_location</code>.
     */
    public ITbUser setGpsLocation(String value);

    /**
     * Getter for <code>public.tb_user.gps_location</code>.
     */
    public String getGpsLocation();

    /**
     * Setter for <code>public.tb_user.dob</code>.
     */
    public ITbUser setDob(String value);

    /**
     * Getter for <code>public.tb_user.dob</code>.
     */
    public String getDob();

    /**
     * Setter for <code>public.tb_user.other_info</code>.
     */
    public ITbUser setOtherInfo(String value);

    /**
     * Getter for <code>public.tb_user.other_info</code>.
     */
    public String getOtherInfo();

    /**
     * Setter for <code>public.tb_user.created_by</code>.
     */
    public ITbUser setCreatedBy(String value);

    /**
     * Getter for <code>public.tb_user.created_by</code>.
     */
    public String getCreatedBy();

    /**
     * Setter for <code>public.tb_user.created_on</code>.
     */
    public ITbUser setCreatedOn(OffsetDateTime value);

    /**
     * Getter for <code>public.tb_user.created_on</code>.
     */
    public OffsetDateTime getCreatedOn();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbUser
     */
    public void from(jooq.tables.interfaces.ITbUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbUser
     */
    public <E extends jooq.tables.interfaces.ITbUser> E into(E into);

    @Override
    public default ITbUser fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setRoleId(json.getString("role_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("role_id","java.lang.String",e);
        }
        try {
            setFirstName(json.getString("first_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("first_name","java.lang.String",e);
        }
        try {
            setLastName(json.getString("last_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("last_name","java.lang.String",e);
        }
        try {
            setEmail(json.getString("email"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("email","java.lang.String",e);
        }
        try {
            setMobile(json.getString("mobile"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("mobile","java.lang.String",e);
        }
        try {
            setHashedPassword(json.getString("hashed_password"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("hashed_password","java.lang.String",e);
        }
        try {
            setSalt(json.getString("salt"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("salt","java.lang.String",e);
        }
        try {
            setProfilePic(json.getString("profile_pic"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("profile_pic","java.lang.String",e);
        }
        try {
            setBackgroundInfo(json.getString("background_info"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("background_info","java.lang.String",e);
        }
        try {
            setWebsite(json.getString("website"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("website","java.lang.String",e);
        }
        try {
            setGpsLocation(json.getString("gps_location"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("gps_location","java.lang.String",e);
        }
        try {
            setDob(json.getString("dob"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("dob","java.lang.String",e);
        }
        try {
            setOtherInfo(json.getString("other_info"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("other_info","java.lang.String",e);
        }
        try {
            setCreatedBy(json.getString("created_by"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_by","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.OffsetDateTime for column created_on!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("created_on","java.time.OffsetDateTime",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("role_id",getRoleId());
        json.put("first_name",getFirstName());
        json.put("last_name",getLastName());
        json.put("email",getEmail());
        json.put("mobile",getMobile());
        json.put("hashed_password",getHashedPassword());
        json.put("salt",getSalt());
        json.put("profile_pic",getProfilePic());
        json.put("background_info",getBackgroundInfo());
        json.put("website",getWebsite());
        json.put("gps_location",getGpsLocation());
        json.put("dob",getDob());
        json.put("other_info",getOtherInfo());
        json.put("created_by",getCreatedBy());
        // Omitting unrecognized type java.time.OffsetDateTime for column created_on!
        return json;
    }

}
