/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbCategory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCategory implements VertxPojo, ITbCategory {

    private static final long serialVersionUID = -1162290769;

    private Long       id;
    private String     cid;
    private String     name;
    private String     description;
    private String     createdBy;
    private OffsetTime createdAt;

    public TbCategory() {}

    public TbCategory(ITbCategory value) {
        this.id = value.getId();
        this.cid = value.getCid();
        this.name = value.getName();
        this.description = value.getDescription();
        this.createdBy = value.getCreatedBy();
        this.createdAt = value.getCreatedAt();
    }

    public TbCategory(
        Long       id,
        String     cid,
        String     name,
        String     description,
        String     createdBy,
        OffsetTime createdAt
    ) {
        this.id = id;
        this.cid = cid;
        this.name = name;
        this.description = description;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbCategory setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getCid() {
        return this.cid;
    }

    @Override
    public TbCategory setCid(String cid) {
        this.cid = cid;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbCategory setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbCategory setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TbCategory setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public OffsetTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbCategory setCreatedAt(OffsetTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbCategory (");

        sb.append(id);
        sb.append(", ").append(cid);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCategory from) {
        setId(from.getId());
        setCid(from.getCid());
        setName(from.getName());
        setDescription(from.getDescription());
        setCreatedBy(from.getCreatedBy());
        setCreatedAt(from.getCreatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCategory> E into(E into) {
        into.from(this);
        return into;
    }

    public TbCategory(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
