/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbCategory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCategory implements VertxPojo, ITbCategory {

    private static final long serialVersionUID = -971071408;

    private Long   id;
    private String cid;
    private String name;
    private String description;
    private String createdby;
    private String createdon;

    public TbCategory() {}

    public TbCategory(ITbCategory value) {
        this.id = value.getId();
        this.cid = value.getCid();
        this.name = value.getName();
        this.description = value.getDescription();
        this.createdby = value.getCreatedby();
        this.createdon = value.getCreatedon();
    }

    public TbCategory(
        Long   id,
        String cid,
        String name,
        String description,
        String createdby,
        String createdon
    ) {
        this.id = id;
        this.cid = cid;
        this.name = name;
        this.description = description;
        this.createdby = createdby;
        this.createdon = createdon;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbCategory setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getCid() {
        return this.cid;
    }

    @Override
    public TbCategory setCid(String cid) {
        this.cid = cid;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbCategory setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbCategory setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getCreatedby() {
        return this.createdby;
    }

    @Override
    public TbCategory setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    @Override
    public String getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbCategory setCreatedon(String createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbCategory (");

        sb.append(id);
        sb.append(", ").append(cid);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdon);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCategory from) {
        setId(from.getId());
        setCid(from.getCid());
        setName(from.getName());
        setDescription(from.getDescription());
        setCreatedby(from.getCreatedby());
        setCreatedon(from.getCreatedon());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCategory> E into(E into) {
        into.from(this);
        return into;
    }

    public TbCategory(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
