/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbComment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbComment implements VertxPojo, ITbComment {

    private static final long serialVersionUID = 1987861294;

    private Long           id;
    private String         authorId;
    private String         cid;
    private String         storyId;
    private Integer        possibilitySensitive;
    private String         lang;
    private OffsetDateTime createdAt;
    private String         entities;
    private String         authorName;

    public TbComment() {}

    public TbComment(ITbComment value) {
        this.id = value.getId();
        this.authorId = value.getAuthorId();
        this.cid = value.getCid();
        this.storyId = value.getStoryId();
        this.possibilitySensitive = value.getPossibilitySensitive();
        this.lang = value.getLang();
        this.createdAt = value.getCreatedAt();
        this.entities = value.getEntities();
        this.authorName = value.getAuthorName();
    }

    public TbComment(
        Long           id,
        String         authorId,
        String         cid,
        String         storyId,
        Integer        possibilitySensitive,
        String         lang,
        OffsetDateTime createdAt,
        String         entities,
        String         authorName
    ) {
        this.id = id;
        this.authorId = authorId;
        this.cid = cid;
        this.storyId = storyId;
        this.possibilitySensitive = possibilitySensitive;
        this.lang = lang;
        this.createdAt = createdAt;
        this.entities = entities;
        this.authorName = authorName;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbComment setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public TbComment setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getCid() {
        return this.cid;
    }

    @Override
    public TbComment setCid(String cid) {
        this.cid = cid;
        return this;
    }

    @Override
    public String getStoryId() {
        return this.storyId;
    }

    @Override
    public TbComment setStoryId(String storyId) {
        this.storyId = storyId;
        return this;
    }

    @Override
    public Integer getPossibilitySensitive() {
        return this.possibilitySensitive;
    }

    @Override
    public TbComment setPossibilitySensitive(Integer possibilitySensitive) {
        this.possibilitySensitive = possibilitySensitive;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbComment setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbComment setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getEntities() {
        return this.entities;
    }

    @Override
    public TbComment setEntities(String entities) {
        this.entities = entities;
        return this;
    }

    @Override
    public String getAuthorName() {
        return this.authorName;
    }

    @Override
    public TbComment setAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComment (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(cid);
        sb.append(", ").append(storyId);
        sb.append(", ").append(possibilitySensitive);
        sb.append(", ").append(lang);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(entities);
        sb.append(", ").append(authorName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbComment from) {
        setId(from.getId());
        setAuthorId(from.getAuthorId());
        setCid(from.getCid());
        setStoryId(from.getStoryId());
        setPossibilitySensitive(from.getPossibilitySensitive());
        setLang(from.getLang());
        setCreatedAt(from.getCreatedAt());
        setEntities(from.getEntities());
        setAuthorName(from.getAuthorName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbComment> E into(E into) {
        into.from(this);
        return into;
    }

    public TbComment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
