/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbComment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbComment implements VertxPojo, ITbComment {

    private static final long serialVersionUID = 153308109;

    private Long           id;
    private String         authorId;
    private String         commentId;
    private String         storyId;
    private Integer        possibilitySensitive;
    private String         lang;
    private OffsetDateTime createdAt;
    private String         entries;

    public TbComment() {}

    public TbComment(ITbComment value) {
        this.id = value.getId();
        this.authorId = value.getAuthorId();
        this.commentId = value.getCommentId();
        this.storyId = value.getStoryId();
        this.possibilitySensitive = value.getPossibilitySensitive();
        this.lang = value.getLang();
        this.createdAt = value.getCreatedAt();
        this.entries = value.getEntries();
    }

    public TbComment(
        Long           id,
        String         authorId,
        String         commentId,
        String         storyId,
        Integer        possibilitySensitive,
        String         lang,
        OffsetDateTime createdAt,
        String         entries
    ) {
        this.id = id;
        this.authorId = authorId;
        this.commentId = commentId;
        this.storyId = storyId;
        this.possibilitySensitive = possibilitySensitive;
        this.lang = lang;
        this.createdAt = createdAt;
        this.entries = entries;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbComment setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public TbComment setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getCommentId() {
        return this.commentId;
    }

    @Override
    public TbComment setCommentId(String commentId) {
        this.commentId = commentId;
        return this;
    }

    @Override
    public String getStoryId() {
        return this.storyId;
    }

    @Override
    public TbComment setStoryId(String storyId) {
        this.storyId = storyId;
        return this;
    }

    @Override
    public Integer getPossibilitySensitive() {
        return this.possibilitySensitive;
    }

    @Override
    public TbComment setPossibilitySensitive(Integer possibilitySensitive) {
        this.possibilitySensitive = possibilitySensitive;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbComment setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbComment setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getEntries() {
        return this.entries;
    }

    @Override
    public TbComment setEntries(String entries) {
        this.entries = entries;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComment (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(commentId);
        sb.append(", ").append(storyId);
        sb.append(", ").append(possibilitySensitive);
        sb.append(", ").append(lang);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(entries);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbComment from) {
        setId(from.getId());
        setAuthorId(from.getAuthorId());
        setCommentId(from.getCommentId());
        setStoryId(from.getStoryId());
        setPossibilitySensitive(from.getPossibilitySensitive());
        setLang(from.getLang());
        setCreatedAt(from.getCreatedAt());
        setEntries(from.getEntries());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbComment> E into(E into) {
        into.from(this);
        return into;
    }

    public TbComment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
