/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbCompany;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCompany implements VertxPojo, ITbCompany {

    private static final long serialVersionUID = -68367283;

    private Long       id;
    private String     name;
    private String     location;
    private String     phoneNumber;
    private String     sector;
    private Integer    rating;
    private String     logo;
    private String     backgroundInfo;
    private String     pictures;
    private String     companyId;
    private String     companyCode;
    private OffsetTime createdAt;
    private String     createdBy;
    private String     email;
    private String     website;
    private String     otherLinks;

    public TbCompany() {}

    public TbCompany(ITbCompany value) {
        this.id = value.getId();
        this.name = value.getName();
        this.location = value.getLocation();
        this.phoneNumber = value.getPhoneNumber();
        this.sector = value.getSector();
        this.rating = value.getRating();
        this.logo = value.getLogo();
        this.backgroundInfo = value.getBackgroundInfo();
        this.pictures = value.getPictures();
        this.companyId = value.getCompanyId();
        this.companyCode = value.getCompanyCode();
        this.createdAt = value.getCreatedAt();
        this.createdBy = value.getCreatedBy();
        this.email = value.getEmail();
        this.website = value.getWebsite();
        this.otherLinks = value.getOtherLinks();
    }

    public TbCompany(
        Long       id,
        String     name,
        String     location,
        String     phoneNumber,
        String     sector,
        Integer    rating,
        String     logo,
        String     backgroundInfo,
        String     pictures,
        String     companyId,
        String     companyCode,
        OffsetTime createdAt,
        String     createdBy,
        String     email,
        String     website,
        String     otherLinks
    ) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.phoneNumber = phoneNumber;
        this.sector = sector;
        this.rating = rating;
        this.logo = logo;
        this.backgroundInfo = backgroundInfo;
        this.pictures = pictures;
        this.companyId = companyId;
        this.companyCode = companyCode;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.email = email;
        this.website = website;
        this.otherLinks = otherLinks;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbCompany setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbCompany setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getLocation() {
        return this.location;
    }

    @Override
    public TbCompany setLocation(String location) {
        this.location = location;
        return this;
    }

    @Override
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @Override
    public TbCompany setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    @Override
    public String getSector() {
        return this.sector;
    }

    @Override
    public TbCompany setSector(String sector) {
        this.sector = sector;
        return this;
    }

    @Override
    public Integer getRating() {
        return this.rating;
    }

    @Override
    public TbCompany setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    @Override
    public String getLogo() {
        return this.logo;
    }

    @Override
    public TbCompany setLogo(String logo) {
        this.logo = logo;
        return this;
    }

    @Override
    public String getBackgroundInfo() {
        return this.backgroundInfo;
    }

    @Override
    public TbCompany setBackgroundInfo(String backgroundInfo) {
        this.backgroundInfo = backgroundInfo;
        return this;
    }

    @Override
    public String getPictures() {
        return this.pictures;
    }

    @Override
    public TbCompany setPictures(String pictures) {
        this.pictures = pictures;
        return this;
    }

    @Override
    public String getCompanyId() {
        return this.companyId;
    }

    @Override
    public TbCompany setCompanyId(String companyId) {
        this.companyId = companyId;
        return this;
    }

    @Override
    public String getCompanyCode() {
        return this.companyCode;
    }

    @Override
    public TbCompany setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
        return this;
    }

    @Override
    public OffsetTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbCompany setCreatedAt(OffsetTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TbCompany setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public TbCompany setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getWebsite() {
        return this.website;
    }

    @Override
    public TbCompany setWebsite(String website) {
        this.website = website;
        return this;
    }

    @Override
    public String getOtherLinks() {
        return this.otherLinks;
    }

    @Override
    public TbCompany setOtherLinks(String otherLinks) {
        this.otherLinks = otherLinks;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbCompany (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(location);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(sector);
        sb.append(", ").append(rating);
        sb.append(", ").append(logo);
        sb.append(", ").append(backgroundInfo);
        sb.append(", ").append(pictures);
        sb.append(", ").append(companyId);
        sb.append(", ").append(companyCode);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(email);
        sb.append(", ").append(website);
        sb.append(", ").append(otherLinks);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCompany from) {
        setId(from.getId());
        setName(from.getName());
        setLocation(from.getLocation());
        setPhoneNumber(from.getPhoneNumber());
        setSector(from.getSector());
        setRating(from.getRating());
        setLogo(from.getLogo());
        setBackgroundInfo(from.getBackgroundInfo());
        setPictures(from.getPictures());
        setCompanyId(from.getCompanyId());
        setCompanyCode(from.getCompanyCode());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setEmail(from.getEmail());
        setWebsite(from.getWebsite());
        setOtherLinks(from.getOtherLinks());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCompany> E into(E into) {
        into.from(this);
        return into;
    }

    public TbCompany(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
