/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbComment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbComment implements VertxPojo, ITbComment {

    private static final long serialVersionUID = 1627443807;

    private Long    id;
    private String  authorid;
    private String  cid;
    private String  storyid;
    private Integer possibilitysensitive;
    private String  lang;
    private String  entities;
    private String  authorname;
    private String  createdon;

    public TbComment() {}

    public TbComment(ITbComment value) {
        this.id = value.getId();
        this.authorid = value.getAuthorid();
        this.cid = value.getCid();
        this.storyid = value.getStoryid();
        this.possibilitysensitive = value.getPossibilitysensitive();
        this.lang = value.getLang();
        this.entities = value.getEntities();
        this.authorname = value.getAuthorname();
        this.createdon = value.getCreatedon();
    }

    public TbComment(
        Long    id,
        String  authorid,
        String  cid,
        String  storyid,
        Integer possibilitysensitive,
        String  lang,
        String  entities,
        String  authorname,
        String  createdon
    ) {
        this.id = id;
        this.authorid = authorid;
        this.cid = cid;
        this.storyid = storyid;
        this.possibilitysensitive = possibilitysensitive;
        this.lang = lang;
        this.entities = entities;
        this.authorname = authorname;
        this.createdon = createdon;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbComment setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorid() {
        return this.authorid;
    }

    @Override
    public TbComment setAuthorid(String authorid) {
        this.authorid = authorid;
        return this;
    }

    @Override
    public String getCid() {
        return this.cid;
    }

    @Override
    public TbComment setCid(String cid) {
        this.cid = cid;
        return this;
    }

    @Override
    public String getStoryid() {
        return this.storyid;
    }

    @Override
    public TbComment setStoryid(String storyid) {
        this.storyid = storyid;
        return this;
    }

    @Override
    public Integer getPossibilitysensitive() {
        return this.possibilitysensitive;
    }

    @Override
    public TbComment setPossibilitysensitive(Integer possibilitysensitive) {
        this.possibilitysensitive = possibilitysensitive;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbComment setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public String getEntities() {
        return this.entities;
    }

    @Override
    public TbComment setEntities(String entities) {
        this.entities = entities;
        return this;
    }

    @Override
    public String getAuthorname() {
        return this.authorname;
    }

    @Override
    public TbComment setAuthorname(String authorname) {
        this.authorname = authorname;
        return this;
    }

    @Override
    public String getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbComment setCreatedon(String createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComment (");

        sb.append(id);
        sb.append(", ").append(authorid);
        sb.append(", ").append(cid);
        sb.append(", ").append(storyid);
        sb.append(", ").append(possibilitysensitive);
        sb.append(", ").append(lang);
        sb.append(", ").append(entities);
        sb.append(", ").append(authorname);
        sb.append(", ").append(createdon);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbComment from) {
        setId(from.getId());
        setAuthorid(from.getAuthorid());
        setCid(from.getCid());
        setStoryid(from.getStoryid());
        setPossibilitysensitive(from.getPossibilitysensitive());
        setLang(from.getLang());
        setEntities(from.getEntities());
        setAuthorname(from.getAuthorname());
        setCreatedon(from.getCreatedon());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbComment> E into(E into) {
        into.from(this);
        return into;
    }

    public TbComment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
