/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbCompany;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCompany implements VertxPojo, ITbCompany {

    private static final long serialVersionUID = 1572296196;

    private Long       id;
    private String     name;
    private String     location;
    private String     phoneNumber;
    private String     sectorName;
    private Integer    rating;
    private String     logo;
    private String     backgroundInfo;
    private String     entities;
    private String     cid;
    private String     code;
    private OffsetTime createdAt;
    private String     createdBy;
    private String     email;
    private String     website;
    private String     otherLinks;
    private String     categoryName;
    private String     sectorId;
    private String     categoryId;

    public TbCompany() {}

    public TbCompany(ITbCompany value) {
        this.id = value.getId();
        this.name = value.getName();
        this.location = value.getLocation();
        this.phoneNumber = value.getPhoneNumber();
        this.sectorName = value.getSectorName();
        this.rating = value.getRating();
        this.logo = value.getLogo();
        this.backgroundInfo = value.getBackgroundInfo();
        this.entities = value.getEntities();
        this.cid = value.getCid();
        this.code = value.getCode();
        this.createdAt = value.getCreatedAt();
        this.createdBy = value.getCreatedBy();
        this.email = value.getEmail();
        this.website = value.getWebsite();
        this.otherLinks = value.getOtherLinks();
        this.categoryName = value.getCategoryName();
        this.sectorId = value.getSectorId();
        this.categoryId = value.getCategoryId();
    }

    public TbCompany(
        Long       id,
        String     name,
        String     location,
        String     phoneNumber,
        String     sectorName,
        Integer    rating,
        String     logo,
        String     backgroundInfo,
        String     entities,
        String     cid,
        String     code,
        OffsetTime createdAt,
        String     createdBy,
        String     email,
        String     website,
        String     otherLinks,
        String     categoryName,
        String     sectorId,
        String     categoryId
    ) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.phoneNumber = phoneNumber;
        this.sectorName = sectorName;
        this.rating = rating;
        this.logo = logo;
        this.backgroundInfo = backgroundInfo;
        this.entities = entities;
        this.cid = cid;
        this.code = code;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.email = email;
        this.website = website;
        this.otherLinks = otherLinks;
        this.categoryName = categoryName;
        this.sectorId = sectorId;
        this.categoryId = categoryId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbCompany setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbCompany setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getLocation() {
        return this.location;
    }

    @Override
    public TbCompany setLocation(String location) {
        this.location = location;
        return this;
    }

    @Override
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @Override
    public TbCompany setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    @Override
    public String getSectorName() {
        return this.sectorName;
    }

    @Override
    public TbCompany setSectorName(String sectorName) {
        this.sectorName = sectorName;
        return this;
    }

    @Override
    public Integer getRating() {
        return this.rating;
    }

    @Override
    public TbCompany setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    @Override
    public String getLogo() {
        return this.logo;
    }

    @Override
    public TbCompany setLogo(String logo) {
        this.logo = logo;
        return this;
    }

    @Override
    public String getBackgroundInfo() {
        return this.backgroundInfo;
    }

    @Override
    public TbCompany setBackgroundInfo(String backgroundInfo) {
        this.backgroundInfo = backgroundInfo;
        return this;
    }

    @Override
    public String getEntities() {
        return this.entities;
    }

    @Override
    public TbCompany setEntities(String entities) {
        this.entities = entities;
        return this;
    }

    @Override
    public String getCid() {
        return this.cid;
    }

    @Override
    public TbCompany setCid(String cid) {
        this.cid = cid;
        return this;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public TbCompany setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public OffsetTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbCompany setCreatedAt(OffsetTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TbCompany setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public TbCompany setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getWebsite() {
        return this.website;
    }

    @Override
    public TbCompany setWebsite(String website) {
        this.website = website;
        return this;
    }

    @Override
    public String getOtherLinks() {
        return this.otherLinks;
    }

    @Override
    public TbCompany setOtherLinks(String otherLinks) {
        this.otherLinks = otherLinks;
        return this;
    }

    @Override
    public String getCategoryName() {
        return this.categoryName;
    }

    @Override
    public TbCompany setCategoryName(String categoryName) {
        this.categoryName = categoryName;
        return this;
    }

    @Override
    public String getSectorId() {
        return this.sectorId;
    }

    @Override
    public TbCompany setSectorId(String sectorId) {
        this.sectorId = sectorId;
        return this;
    }

    @Override
    public String getCategoryId() {
        return this.categoryId;
    }

    @Override
    public TbCompany setCategoryId(String categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbCompany (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(location);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(sectorName);
        sb.append(", ").append(rating);
        sb.append(", ").append(logo);
        sb.append(", ").append(backgroundInfo);
        sb.append(", ").append(entities);
        sb.append(", ").append(cid);
        sb.append(", ").append(code);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(email);
        sb.append(", ").append(website);
        sb.append(", ").append(otherLinks);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(sectorId);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCompany from) {
        setId(from.getId());
        setName(from.getName());
        setLocation(from.getLocation());
        setPhoneNumber(from.getPhoneNumber());
        setSectorName(from.getSectorName());
        setRating(from.getRating());
        setLogo(from.getLogo());
        setBackgroundInfo(from.getBackgroundInfo());
        setEntities(from.getEntities());
        setCid(from.getCid());
        setCode(from.getCode());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setEmail(from.getEmail());
        setWebsite(from.getWebsite());
        setOtherLinks(from.getOtherLinks());
        setCategoryName(from.getCategoryName());
        setSectorId(from.getSectorId());
        setCategoryId(from.getCategoryId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCompany> E into(E into) {
        into.from(this);
        return into;
    }

    public TbCompany(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
