/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbInterest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbInterest implements VertxPojo, ITbInterest {

    private static final long serialVersionUID = -1708098396;

    private Long      id;
    private String    iid;
    private String    description;
    private String    name;
    private String    createdby;
    private Timestamp createdon;

    public TbInterest() {}

    public TbInterest(ITbInterest value) {
        this.id = value.getId();
        this.iid = value.getIid();
        this.description = value.getDescription();
        this.name = value.getName();
        this.createdby = value.getCreatedby();
        this.createdon = value.getCreatedon();
    }

    public TbInterest(
        Long      id,
        String    iid,
        String    description,
        String    name,
        String    createdby,
        Timestamp createdon
    ) {
        this.id = id;
        this.iid = iid;
        this.description = description;
        this.name = name;
        this.createdby = createdby;
        this.createdon = createdon;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbInterest setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getIid() {
        return this.iid;
    }

    @Override
    public TbInterest setIid(String iid) {
        this.iid = iid;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbInterest setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbInterest setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCreatedby() {
        return this.createdby;
    }

    @Override
    public TbInterest setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    @Override
    public Timestamp getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbInterest setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbInterest (");

        sb.append(id);
        sb.append(", ").append(iid);
        sb.append(", ").append(description);
        sb.append(", ").append(name);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdon);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbInterest from) {
        setId(from.getId());
        setIid(from.getIid());
        setDescription(from.getDescription());
        setName(from.getName());
        setCreatedby(from.getCreatedby());
        setCreatedon(from.getCreatedon());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbInterest> E into(E into) {
        into.from(this);
        return into;
    }

    public TbInterest(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
