/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbLikes;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbLikes implements VertxPojo, ITbLikes {

    private static final long serialVersionUID = -24379828;

    private Long    id;
    private String  authorid;
    private String  lid;
    private String  commentId;
    private String  storyid;
    private Integer possibilitysensitive;
    private String  lang;
    private String  entities;
    private String  authorname;
    private String  createdon;
    private String  status;

    public TbLikes() {}

    public TbLikes(ITbLikes value) {
        this.id = value.getId();
        this.authorid = value.getAuthorid();
        this.lid = value.getLid();
        this.commentId = value.getCommentId();
        this.storyid = value.getStoryid();
        this.possibilitysensitive = value.getPossibilitysensitive();
        this.lang = value.getLang();
        this.entities = value.getEntities();
        this.authorname = value.getAuthorname();
        this.createdon = value.getCreatedon();
        this.status = value.getStatus();
    }

    public TbLikes(
        Long    id,
        String  authorid,
        String  lid,
        String  commentId,
        String  storyid,
        Integer possibilitysensitive,
        String  lang,
        String  entities,
        String  authorname,
        String  createdon,
        String  status
    ) {
        this.id = id;
        this.authorid = authorid;
        this.lid = lid;
        this.commentId = commentId;
        this.storyid = storyid;
        this.possibilitysensitive = possibilitysensitive;
        this.lang = lang;
        this.entities = entities;
        this.authorname = authorname;
        this.createdon = createdon;
        this.status = status;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbLikes setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorid() {
        return this.authorid;
    }

    @Override
    public TbLikes setAuthorid(String authorid) {
        this.authorid = authorid;
        return this;
    }

    @Override
    public String getLid() {
        return this.lid;
    }

    @Override
    public TbLikes setLid(String lid) {
        this.lid = lid;
        return this;
    }

    @Override
    public String getCommentId() {
        return this.commentId;
    }

    @Override
    public TbLikes setCommentId(String commentId) {
        this.commentId = commentId;
        return this;
    }

    @Override
    public String getStoryid() {
        return this.storyid;
    }

    @Override
    public TbLikes setStoryid(String storyid) {
        this.storyid = storyid;
        return this;
    }

    @Override
    public Integer getPossibilitysensitive() {
        return this.possibilitysensitive;
    }

    @Override
    public TbLikes setPossibilitysensitive(Integer possibilitysensitive) {
        this.possibilitysensitive = possibilitysensitive;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbLikes setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public String getEntities() {
        return this.entities;
    }

    @Override
    public TbLikes setEntities(String entities) {
        this.entities = entities;
        return this;
    }

    @Override
    public String getAuthorname() {
        return this.authorname;
    }

    @Override
    public TbLikes setAuthorname(String authorname) {
        this.authorname = authorname;
        return this;
    }

    @Override
    public String getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbLikes setCreatedon(String createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TbLikes setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbLikes (");

        sb.append(id);
        sb.append(", ").append(authorid);
        sb.append(", ").append(lid);
        sb.append(", ").append(commentId);
        sb.append(", ").append(storyid);
        sb.append(", ").append(possibilitysensitive);
        sb.append(", ").append(lang);
        sb.append(", ").append(entities);
        sb.append(", ").append(authorname);
        sb.append(", ").append(createdon);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbLikes from) {
        setId(from.getId());
        setAuthorid(from.getAuthorid());
        setLid(from.getLid());
        setCommentId(from.getCommentId());
        setStoryid(from.getStoryid());
        setPossibilitysensitive(from.getPossibilitysensitive());
        setLang(from.getLang());
        setEntities(from.getEntities());
        setAuthorname(from.getAuthorname());
        setCreatedon(from.getCreatedon());
        setStatus(from.getStatus());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbLikes> E into(E into) {
        into.from(this);
        return into;
    }

    public TbLikes(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
