/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbSector;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbSector implements VertxPojo, ITbSector {

    private static final long serialVersionUID = -591953126;

    private Long   id;
    private String sid;
    private String name;
    private String createdby;
    private String description;
    private String createdon;

    public TbSector() {}

    public TbSector(ITbSector value) {
        this.id = value.getId();
        this.sid = value.getSid();
        this.name = value.getName();
        this.createdby = value.getCreatedby();
        this.description = value.getDescription();
        this.createdon = value.getCreatedon();
    }

    public TbSector(
        Long   id,
        String sid,
        String name,
        String createdby,
        String description,
        String createdon
    ) {
        this.id = id;
        this.sid = sid;
        this.name = name;
        this.createdby = createdby;
        this.description = description;
        this.createdon = createdon;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbSector setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getSid() {
        return this.sid;
    }

    @Override
    public TbSector setSid(String sid) {
        this.sid = sid;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbSector setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCreatedby() {
        return this.createdby;
    }

    @Override
    public TbSector setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbSector setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbSector setCreatedon(String createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbSector (");

        sb.append(id);
        sb.append(", ").append(sid);
        sb.append(", ").append(name);
        sb.append(", ").append(createdby);
        sb.append(", ").append(description);
        sb.append(", ").append(createdon);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbSector from) {
        setId(from.getId());
        setSid(from.getSid());
        setName(from.getName());
        setCreatedby(from.getCreatedby());
        setDescription(from.getDescription());
        setCreatedon(from.getCreatedon());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbSector> E into(E into) {
        into.from(this);
        return into;
    }

    public TbSector(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
