/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbSector;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbSector implements VertxPojo, ITbSector {

    private static final long serialVersionUID = 1754480799;

    private Long       id;
    private String     sid;
    private String     name;
    private String     createdBy;
    private OffsetTime createdAt;
    private String     description;

    public TbSector() {}

    public TbSector(ITbSector value) {
        this.id = value.getId();
        this.sid = value.getSid();
        this.name = value.getName();
        this.createdBy = value.getCreatedBy();
        this.createdAt = value.getCreatedAt();
        this.description = value.getDescription();
    }

    public TbSector(
        Long       id,
        String     sid,
        String     name,
        String     createdBy,
        OffsetTime createdAt,
        String     description
    ) {
        this.id = id;
        this.sid = sid;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.description = description;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbSector setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getSid() {
        return this.sid;
    }

    @Override
    public TbSector setSid(String sid) {
        this.sid = sid;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbSector setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TbSector setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public OffsetTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbSector setCreatedAt(OffsetTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbSector setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbSector (");

        sb.append(id);
        sb.append(", ").append(sid);
        sb.append(", ").append(name);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbSector from) {
        setId(from.getId());
        setSid(from.getSid());
        setName(from.getName());
        setCreatedBy(from.getCreatedBy());
        setCreatedAt(from.getCreatedAt());
        setDescription(from.getDescription());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbSector> E into(E into) {
        into.from(this);
        return into;
    }

    public TbSector(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
