/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbStory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbStory implements VertxPojo, ITbStory {

    private static final long serialVersionUID = 767265626;

    private Long           id;
    private String         authorId;
    private String         entities;
    private String         sid;
    private String         lang;
    private Integer        possiblySensitive;
    private String         source;
    private String         story;
    private OffsetDateTime createdAt;
    private Integer        likeCount;
    private Integer        commentCount;
    private Integer        cautionCount;
    private String         categoryName;
    private String         sectorName;
    private String         companyId;
    private String         sectorId;
    private String         categoryId;
    private String         authorName;

    public TbStory() {}

    public TbStory(ITbStory value) {
        this.id = value.getId();
        this.authorId = value.getAuthorId();
        this.entities = value.getEntities();
        this.sid = value.getSid();
        this.lang = value.getLang();
        this.possiblySensitive = value.getPossiblySensitive();
        this.source = value.getSource();
        this.story = value.getStory();
        this.createdAt = value.getCreatedAt();
        this.likeCount = value.getLikeCount();
        this.commentCount = value.getCommentCount();
        this.cautionCount = value.getCautionCount();
        this.categoryName = value.getCategoryName();
        this.sectorName = value.getSectorName();
        this.companyId = value.getCompanyId();
        this.sectorId = value.getSectorId();
        this.categoryId = value.getCategoryId();
        this.authorName = value.getAuthorName();
    }

    public TbStory(
        Long           id,
        String         authorId,
        String         entities,
        String         sid,
        String         lang,
        Integer        possiblySensitive,
        String         source,
        String         story,
        OffsetDateTime createdAt,
        Integer        likeCount,
        Integer        commentCount,
        Integer        cautionCount,
        String         categoryName,
        String         sectorName,
        String         companyId,
        String         sectorId,
        String         categoryId,
        String         authorName
    ) {
        this.id = id;
        this.authorId = authorId;
        this.entities = entities;
        this.sid = sid;
        this.lang = lang;
        this.possiblySensitive = possiblySensitive;
        this.source = source;
        this.story = story;
        this.createdAt = createdAt;
        this.likeCount = likeCount;
        this.commentCount = commentCount;
        this.cautionCount = cautionCount;
        this.categoryName = categoryName;
        this.sectorName = sectorName;
        this.companyId = companyId;
        this.sectorId = sectorId;
        this.categoryId = categoryId;
        this.authorName = authorName;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbStory setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public TbStory setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getEntities() {
        return this.entities;
    }

    @Override
    public TbStory setEntities(String entities) {
        this.entities = entities;
        return this;
    }

    @Override
    public String getSid() {
        return this.sid;
    }

    @Override
    public TbStory setSid(String sid) {
        this.sid = sid;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbStory setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public Integer getPossiblySensitive() {
        return this.possiblySensitive;
    }

    @Override
    public TbStory setPossiblySensitive(Integer possiblySensitive) {
        this.possiblySensitive = possiblySensitive;
        return this;
    }

    @Override
    public String getSource() {
        return this.source;
    }

    @Override
    public TbStory setSource(String source) {
        this.source = source;
        return this;
    }

    @Override
    public String getStory() {
        return this.story;
    }

    @Override
    public TbStory setStory(String story) {
        this.story = story;
        return this;
    }

    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbStory setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Integer getLikeCount() {
        return this.likeCount;
    }

    @Override
    public TbStory setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
        return this;
    }

    @Override
    public Integer getCommentCount() {
        return this.commentCount;
    }

    @Override
    public TbStory setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
        return this;
    }

    @Override
    public Integer getCautionCount() {
        return this.cautionCount;
    }

    @Override
    public TbStory setCautionCount(Integer cautionCount) {
        this.cautionCount = cautionCount;
        return this;
    }

    @Override
    public String getCategoryName() {
        return this.categoryName;
    }

    @Override
    public TbStory setCategoryName(String categoryName) {
        this.categoryName = categoryName;
        return this;
    }

    @Override
    public String getSectorName() {
        return this.sectorName;
    }

    @Override
    public TbStory setSectorName(String sectorName) {
        this.sectorName = sectorName;
        return this;
    }

    @Override
    public String getCompanyId() {
        return this.companyId;
    }

    @Override
    public TbStory setCompanyId(String companyId) {
        this.companyId = companyId;
        return this;
    }

    @Override
    public String getSectorId() {
        return this.sectorId;
    }

    @Override
    public TbStory setSectorId(String sectorId) {
        this.sectorId = sectorId;
        return this;
    }

    @Override
    public String getCategoryId() {
        return this.categoryId;
    }

    @Override
    public TbStory setCategoryId(String categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    @Override
    public String getAuthorName() {
        return this.authorName;
    }

    @Override
    public TbStory setAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbStory (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(entities);
        sb.append(", ").append(sid);
        sb.append(", ").append(lang);
        sb.append(", ").append(possiblySensitive);
        sb.append(", ").append(source);
        sb.append(", ").append(story);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(likeCount);
        sb.append(", ").append(commentCount);
        sb.append(", ").append(cautionCount);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(sectorName);
        sb.append(", ").append(companyId);
        sb.append(", ").append(sectorId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(authorName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbStory from) {
        setId(from.getId());
        setAuthorId(from.getAuthorId());
        setEntities(from.getEntities());
        setSid(from.getSid());
        setLang(from.getLang());
        setPossiblySensitive(from.getPossiblySensitive());
        setSource(from.getSource());
        setStory(from.getStory());
        setCreatedAt(from.getCreatedAt());
        setLikeCount(from.getLikeCount());
        setCommentCount(from.getCommentCount());
        setCautionCount(from.getCautionCount());
        setCategoryName(from.getCategoryName());
        setSectorName(from.getSectorName());
        setCompanyId(from.getCompanyId());
        setSectorId(from.getSectorId());
        setCategoryId(from.getCategoryId());
        setAuthorName(from.getAuthorName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbStory> E into(E into) {
        into.from(this);
        return into;
    }

    public TbStory(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
