/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbStory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbStory implements VertxPojo, ITbStory {

    private static final long serialVersionUID = -707297887;

    private Long           id;
    private String         authorId;
    private String         entries;
    private String         storyId;
    private String         lang;
    private Integer        possiblySensitive;
    private String         source;
    private String         story;
    private OffsetDateTime createdAt;
    private Integer        likeCount;
    private Integer        commentCount;
    private Integer        cautionCount;

    public TbStory() {}

    public TbStory(ITbStory value) {
        this.id = value.getId();
        this.authorId = value.getAuthorId();
        this.entries = value.getEntries();
        this.storyId = value.getStoryId();
        this.lang = value.getLang();
        this.possiblySensitive = value.getPossiblySensitive();
        this.source = value.getSource();
        this.story = value.getStory();
        this.createdAt = value.getCreatedAt();
        this.likeCount = value.getLikeCount();
        this.commentCount = value.getCommentCount();
        this.cautionCount = value.getCautionCount();
    }

    public TbStory(
        Long           id,
        String         authorId,
        String         entries,
        String         storyId,
        String         lang,
        Integer        possiblySensitive,
        String         source,
        String         story,
        OffsetDateTime createdAt,
        Integer        likeCount,
        Integer        commentCount,
        Integer        cautionCount
    ) {
        this.id = id;
        this.authorId = authorId;
        this.entries = entries;
        this.storyId = storyId;
        this.lang = lang;
        this.possiblySensitive = possiblySensitive;
        this.source = source;
        this.story = story;
        this.createdAt = createdAt;
        this.likeCount = likeCount;
        this.commentCount = commentCount;
        this.cautionCount = cautionCount;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbStory setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public TbStory setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public String getEntries() {
        return this.entries;
    }

    @Override
    public TbStory setEntries(String entries) {
        this.entries = entries;
        return this;
    }

    @Override
    public String getStoryId() {
        return this.storyId;
    }

    @Override
    public TbStory setStoryId(String storyId) {
        this.storyId = storyId;
        return this;
    }

    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public TbStory setLang(String lang) {
        this.lang = lang;
        return this;
    }

    @Override
    public Integer getPossiblySensitive() {
        return this.possiblySensitive;
    }

    @Override
    public TbStory setPossiblySensitive(Integer possiblySensitive) {
        this.possiblySensitive = possiblySensitive;
        return this;
    }

    @Override
    public String getSource() {
        return this.source;
    }

    @Override
    public TbStory setSource(String source) {
        this.source = source;
        return this;
    }

    @Override
    public String getStory() {
        return this.story;
    }

    @Override
    public TbStory setStory(String story) {
        this.story = story;
        return this;
    }

    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TbStory setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Integer getLikeCount() {
        return this.likeCount;
    }

    @Override
    public TbStory setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
        return this;
    }

    @Override
    public Integer getCommentCount() {
        return this.commentCount;
    }

    @Override
    public TbStory setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
        return this;
    }

    @Override
    public Integer getCautionCount() {
        return this.cautionCount;
    }

    @Override
    public TbStory setCautionCount(Integer cautionCount) {
        this.cautionCount = cautionCount;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbStory (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(entries);
        sb.append(", ").append(storyId);
        sb.append(", ").append(lang);
        sb.append(", ").append(possiblySensitive);
        sb.append(", ").append(source);
        sb.append(", ").append(story);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(likeCount);
        sb.append(", ").append(commentCount);
        sb.append(", ").append(cautionCount);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbStory from) {
        setId(from.getId());
        setAuthorId(from.getAuthorId());
        setEntries(from.getEntries());
        setStoryId(from.getStoryId());
        setLang(from.getLang());
        setPossiblySensitive(from.getPossiblySensitive());
        setSource(from.getSource());
        setStory(from.getStory());
        setCreatedAt(from.getCreatedAt());
        setLikeCount(from.getLikeCount());
        setCommentCount(from.getCommentCount());
        setCautionCount(from.getCautionCount());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbStory> E into(E into) {
        into.from(this);
        return into;
    }

    public TbStory(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
