/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbStory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_ID_UQX = Indexes0.AUTHOR_ID_UQX;
    public static final Index TB_STORY_PKEY = Indexes0.TB_STORY_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHOR_ID_UQX = Internal.createIndex("author_id_uqx", TbStory.TB_STORY, new OrderField[] { TbStory.TB_STORY.AUTHOR_ID }, true);
        public static Index TB_STORY_PKEY = Internal.createIndex("tb_story_pkey", TbStory.TB_STORY, new OrderField[] { TbStory.TB_STORY.ID }, true);
    }
}
