/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.sector_id_seq</code>
     */
    public static final Sequence<Long> SECTOR_ID_SEQ = new SequenceImpl<Long>("sector_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tb_category_id_seq</code>
     */
    public static final Sequence<Long> TB_CATEGORY_ID_SEQ = new SequenceImpl<Long>("tb_category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tb_comment_id_seq</code>
     */
    public static final Sequence<Long> TB_COMMENT_ID_SEQ = new SequenceImpl<Long>("tb_comment_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tb_company_id_seq</code>
     */
    public static final Sequence<Long> TB_COMPANY_ID_SEQ = new SequenceImpl<Long>("tb_company_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tb_story_id_seq</code>
     */
    public static final Sequence<Long> TB_STORY_ID_SEQ = new SequenceImpl<Long>("tb_story_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tb_user_id_seq</code>
     */
    public static final Sequence<Long> TB_USER_ID_SEQ = new SequenceImpl<Long>("tb_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
