/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbCategory;
import jooq.tables.TbComment;
import jooq.tables.TbCompany;
import jooq.tables.TbInterest;
import jooq.tables.TbLikes;
import jooq.tables.TbSector;
import jooq.tables.TbStory;
import jooq.tables.TbUser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_category</code>.
     */
    public static final TbCategory TB_CATEGORY = jooq.tables.TbCategory.TB_CATEGORY;

    /**
     * The table <code>public.tb_comment</code>.
     */
    public static final TbComment TB_COMMENT = jooq.tables.TbComment.TB_COMMENT;

    /**
     * The table <code>public.tb_company</code>.
     */
    public static final TbCompany TB_COMPANY = jooq.tables.TbCompany.TB_COMPANY;

    /**
     * The table <code>public.tb_interest</code>.
     */
    public static final TbInterest TB_INTEREST = jooq.tables.TbInterest.TB_INTEREST;

    /**
     * The table <code>public.tb_likes</code>.
     */
    public static final TbLikes TB_LIKES = jooq.tables.TbLikes.TB_LIKES;

    /**
     * The table <code>public.tb_sector</code>.
     */
    public static final TbSector TB_SECTOR = jooq.tables.TbSector.TB_SECTOR;

    /**
     * The table <code>public.tb_story</code>.
     */
    public static final TbStory TB_STORY = jooq.tables.TbStory.TB_STORY;

    /**
     * The table <code>public.tb_user</code>.
     */
    public static final TbUser TB_USER = jooq.tables.TbUser.TB_USER;
}
