/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbComment;
import jooq.tables.TbCompany;
import jooq.tables.TbStory;
import jooq.tables.TbUser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_comment</code>.
     */
    public static final TbComment TB_COMMENT = jooq.tables.TbComment.TB_COMMENT;

    /**
     * The table <code>public.tb_company</code>.
     */
    public static final TbCompany TB_COMPANY = jooq.tables.TbCompany.TB_COMPANY;

    /**
     * The table <code>public.tb_story</code>.
     */
    public static final TbStory TB_STORY = jooq.tables.TbStory.TB_STORY;

    /**
     * The table <code>public.tb_user</code>.
     */
    public static final TbUser TB_USER = jooq.tables.TbUser.TB_USER;
}
