version: "3"
services:

  pg_db:
    image: postgres:13
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  story-microservice:
    image: ms-saysay/story-microservice
    links:
      - pg_db
    depends_on:
      - pg_db
    expose:
      - "8082"
  
  administration-microservice:
    image: ms-saysay/administration-microservice
    links:
      - pg_db
    depends_on:
      - pg_db
    expose:
      - "8083"

  comment-microservice:
    image: ms-saysay/comment-microservice
    links:
      - pg_db
    depends_on:
      - pg_db
    expose:
      - "8084"

  likes-microservice:
    image: ms-saysay/likes-microservice
    links:
      - pg_db
    depends_on:
      - pg_db
    expose:
      - "8085"

  api-gateway:
    image: ms-saysay/api-gateway
    ports:
      - 8787:8787
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    links:
      - story-microservice
      - administration-microservice
      - comment-microservice
      - likes-microservice

volumes:
  esdata1:
    driver: local


