version: "3"
services:

  pg_db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  story-microservice:
    image: ms-saysay/story-microservice
    links:
      - pg_db
    depends_on:
      - pg_db
    expose:
      - "8082"

  api-gateway:
    image: ms-saysay/api-gateway
    ports:
      - 8787:8787
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    links:
      - story-microservice

volumes:
  esdata1:
    driver: local


