/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.async.AbstractAsyncVertxDAO;

import java.util.Collection;

import javax.annotation.Generated;

import jooq.tables.TbComment;
import jooq.tables.records.TbCommentRecord;

import org.jooq.Configuration;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.async.AsyncClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCommentDao extends AbstractAsyncVertxDAO<TbCommentRecord, jooq.tables.pojos.TbComment, Long, Future<List<jooq.tables.pojos.TbComment>>, Future<jooq.tables.pojos.TbComment>, Future<Integer>, Future<Long>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<TbCommentRecord,jooq.tables.pojos.TbComment,Long> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TbCommentDao(Configuration configuration, io.vertx.ext.asyncsql.AsyncSQLClient delegate) {
        super(TbComment.TB_COMMENT, jooq.tables.pojos.TbComment.class, new AsyncClassicQueryExecutor<TbCommentRecord,jooq.tables.pojos.TbComment,Long>(configuration,delegate,jooq.tables.pojos.TbComment::new, TbComment.TB_COMMENT));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.tables.pojos.TbComment object) {
        return object.getId();
    }

    /**
     * Find records that have <code>authorid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByAuthorid(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.AUTHORID.in(values));
    }

    /**
     * Find records that have <code>cid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByCid(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.CID.in(values));
    }

    /**
     * Find records that have <code>storyid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByStoryid(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.STORYID.in(values));
    }

    /**
     * Find records that have <code>possibilitysensitive IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByPossibilitysensitive(Collection<Integer> values) {
        return findManyByCondition(TbComment.TB_COMMENT.POSSIBILITYSENSITIVE.in(values));
    }

    /**
     * Find records that have <code>lang IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByLang(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.LANG.in(values));
    }

    /**
     * Find records that have <code>entities IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByEntities(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.ENTITIES.in(values));
    }

    /**
     * Find records that have <code>authorname IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByAuthorname(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.AUTHORNAME.in(values));
    }

    /**
     * Find records that have <code>createdon IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbComment>> findManyByCreatedon(Collection<String> values) {
        return findManyByCondition(TbComment.TB_COMMENT.CREATEDON.in(values));
    }

    @Override
    public AsyncClassicQueryExecutor<TbCommentRecord,jooq.tables.pojos.TbComment,Long> queryExecutor(){
        return (AsyncClassicQueryExecutor<TbCommentRecord,jooq.tables.pojos.TbComment,Long>) super.queryExecutor();
    }

    @Override
    protected java.util.function.Function<Object,Long> keyConverter(){
        return lastId -> Long.valueOf(((io.vertx.core.json.JsonArray)lastId).getLong(0).longValue());
    }
}
