/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.async.AbstractAsyncVertxDAO;

import java.util.Collection;

import javax.annotation.Generated;

import jooq.tables.TbStory;
import jooq.tables.records.TbStoryRecord;

import org.jooq.Configuration;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.async.AsyncClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbStoryDao extends AbstractAsyncVertxDAO<TbStoryRecord, jooq.tables.pojos.TbStory, Long, Future<List<jooq.tables.pojos.TbStory>>, Future<jooq.tables.pojos.TbStory>, Future<Integer>, Future<Long>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<TbStoryRecord,jooq.tables.pojos.TbStory,Long> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TbStoryDao(Configuration configuration, io.vertx.ext.asyncsql.AsyncSQLClient delegate) {
        super(TbStory.TB_STORY, jooq.tables.pojos.TbStory.class, new AsyncClassicQueryExecutor<TbStoryRecord,jooq.tables.pojos.TbStory,Long>(configuration,delegate,jooq.tables.pojos.TbStory::new, TbStory.TB_STORY));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.tables.pojos.TbStory object) {
        return object.getId();
    }

    /**
     * Find records that have <code>authorid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByAuthorid(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.AUTHORID.in(values));
    }

    /**
     * Find records that have <code>entities IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByEntities(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.ENTITIES.in(values));
    }

    /**
     * Find records that have <code>sid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyBySid(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.SID.in(values));
    }

    /**
     * Find records that have <code>lang IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByLang(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.LANG.in(values));
    }

    /**
     * Find records that have <code>possiblysensitive IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByPossiblysensitive(Collection<Integer> values) {
        return findManyByCondition(TbStory.TB_STORY.POSSIBLYSENSITIVE.in(values));
    }

    /**
     * Find records that have <code>source IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyBySource(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.SOURCE.in(values));
    }

    /**
     * Find records that have <code>story IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByStory(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.STORY.in(values));
    }

    /**
     * Find records that have <code>likecount IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByLikecount(Collection<Integer> values) {
        return findManyByCondition(TbStory.TB_STORY.LIKECOUNT.in(values));
    }

    /**
     * Find records that have <code>commentcount IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCommentcount(Collection<Integer> values) {
        return findManyByCondition(TbStory.TB_STORY.COMMENTCOUNT.in(values));
    }

    /**
     * Find records that have <code>cautioncount IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCautioncount(Collection<Integer> values) {
        return findManyByCondition(TbStory.TB_STORY.CAUTIONCOUNT.in(values));
    }

    /**
     * Find records that have <code>categoryname IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCategoryname(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.CATEGORYNAME.in(values));
    }

    /**
     * Find records that have <code>sectorname IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyBySectorname(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.SECTORNAME.in(values));
    }

    /**
     * Find records that have <code>companyid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCompanyid(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.COMPANYID.in(values));
    }

    /**
     * Find records that have <code>sectorid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyBySectorid(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.SECTORID.in(values));
    }

    /**
     * Find records that have <code>categoryid IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCategoryid(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.CATEGORYID.in(values));
    }

    /**
     * Find records that have <code>authorname IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByAuthorname(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.AUTHORNAME.in(values));
    }

    /**
     * Find records that have <code>companyname IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCompanyname(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.COMPANYNAME.in(values));
    }

    /**
     * Find records that have <code>createdon IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByCreatedon(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.CREATEDON.in(values));
    }

    /**
     * Find records that have <code>gpslocation IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbStory>> findManyByGpslocation(Collection<String> values) {
        return findManyByCondition(TbStory.TB_STORY.GPSLOCATION.in(values));
    }

    /**
     * Find a unique record that has <code>sid = value</code> asynchronously
     */
    public Future<jooq.tables.pojos.TbStory> findOneBySid(String value) {
        return findOneByCondition(TbStory.TB_STORY.SID.eq(value));
    }

    @Override
    public AsyncClassicQueryExecutor<TbStoryRecord,jooq.tables.pojos.TbStory,Long> queryExecutor(){
        return (AsyncClassicQueryExecutor<TbStoryRecord,jooq.tables.pojos.TbStory,Long>) super.queryExecutor();
    }

    @Override
    protected java.util.function.Function<Object,Long> keyConverter(){
        return lastId -> Long.valueOf(((io.vertx.core.json.JsonArray)lastId).getLong(0).longValue());
    }
}
