/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.tables.records.TbCategoryRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCategory extends TableImpl<TbCategoryRecord> {

    private static final long serialVersionUID = -1550188498;

    /**
     * The reference instance of <code>public.tb_category</code>
     */
    public static final TbCategory TB_CATEGORY = new TbCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbCategoryRecord> getRecordType() {
        return TbCategoryRecord.class;
    }

    /**
     * The column <code>public.tb_category.id</code>.
     */
    public final TableField<TbCategoryRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('tb_category_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.tb_category.cid</code>.
     */
    public final TableField<TbCategoryRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.tb_category.name</code>.
     */
    public final TableField<TbCategoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_category.description</code>.
     */
    public final TableField<TbCategoryRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_category.createdby</code>.
     */
    public final TableField<TbCategoryRecord, String> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_category.createdon</code>.
     */
    public final TableField<TbCategoryRecord, String> CREATEDON = createField("createdon", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.tb_category</code> table reference
     */
    public TbCategory() {
        this(DSL.name("tb_category"), null);
    }

    /**
     * Create an aliased <code>public.tb_category</code> table reference
     */
    public TbCategory(String alias) {
        this(DSL.name(alias), TB_CATEGORY);
    }

    /**
     * Create an aliased <code>public.tb_category</code> table reference
     */
    public TbCategory(Name alias) {
        this(alias, TB_CATEGORY);
    }

    private TbCategory(Name alias, Table<TbCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbCategory(Name alias, Table<TbCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TbCategory(Table<O> child, ForeignKey<O, TbCategoryRecord> key) {
        super(child, key, TB_CATEGORY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_CATEGORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TbCategoryRecord, Long> getIdentity() {
        return Keys.IDENTITY_TB_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbCategoryRecord> getPrimaryKey() {
        return Keys.TB_CATEGORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<TbCategoryRecord>>asList(Keys.TB_CATEGORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategory as(String alias) {
        return new TbCategory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategory as(Name alias) {
        return new TbCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCategory rename(String name) {
        return new TbCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCategory rename(Name name) {
        return new TbCategory(name, null);
    }
}
