/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.tables.records.TbInterestRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbInterest extends TableImpl<TbInterestRecord> {

    private static final long serialVersionUID = -1981822501;

    /**
     * The reference instance of <code>public.tb_interest</code>
     */
    public static final TbInterest TB_INTEREST = new TbInterest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbInterestRecord> getRecordType() {
        return TbInterestRecord.class;
    }

    /**
     * The column <code>public.tb_interest.id</code>.
     */
    public final TableField<TbInterestRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('tb_interest_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.tb_interest.iid</code>.
     */
    public final TableField<TbInterestRecord, String> IID = createField("iid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.tb_interest.description</code>.
     */
    public final TableField<TbInterestRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_interest.name</code>.
     */
    public final TableField<TbInterestRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_interest.createdby</code>.
     */
    public final TableField<TbInterestRecord, String> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_interest.createdon</code>.
     */
    public final TableField<TbInterestRecord, Timestamp> CREATEDON = createField("createdon", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.tb_interest</code> table reference
     */
    public TbInterest() {
        this(DSL.name("tb_interest"), null);
    }

    /**
     * Create an aliased <code>public.tb_interest</code> table reference
     */
    public TbInterest(String alias) {
        this(DSL.name(alias), TB_INTEREST);
    }

    /**
     * Create an aliased <code>public.tb_interest</code> table reference
     */
    public TbInterest(Name alias) {
        this(alias, TB_INTEREST);
    }

    private TbInterest(Name alias, Table<TbInterestRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbInterest(Name alias, Table<TbInterestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TbInterest(Table<O> child, ForeignKey<O, TbInterestRecord> key) {
        super(child, key, TB_INTEREST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_INTEREST_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TbInterestRecord, Long> getIdentity() {
        return Keys.IDENTITY_TB_INTEREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbInterestRecord> getPrimaryKey() {
        return Keys.TB_INTEREST_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbInterestRecord>> getKeys() {
        return Arrays.<UniqueKey<TbInterestRecord>>asList(Keys.TB_INTEREST_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInterest as(String alias) {
        return new TbInterest(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInterest as(Name alias) {
        return new TbInterest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbInterest rename(String name) {
        return new TbInterest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbInterest rename(Name name) {
        return new TbInterest(name, null);
    }
}
