/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.TbCategory;
import jooq.tables.interfaces.ITbCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCategoryRecord extends UpdatableRecordImpl<TbCategoryRecord> implements VertxPojo, Record6<Long, String, String, String, String, OffsetTime>, ITbCategory {

    private static final long serialVersionUID = -1727987106;

    /**
     * Setter for <code>public.tb_category.id</code>.
     */
    @Override
    public TbCategoryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_category.cid</code>.
     */
    @Override
    public TbCategoryRecord setCid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.cid</code>.
     */
    @Override
    public String getCid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_category.name</code>.
     */
    @Override
    public TbCategoryRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_category.description</code>.
     */
    @Override
    public TbCategoryRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_category.created_by</code>.
     */
    @Override
    public TbCategoryRecord setCreatedBy(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.created_by</code>.
     */
    @Override
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_category.created_at</code>.
     */
    @Override
    public TbCategoryRecord setCreatedAt(OffsetTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_category.created_at</code>.
     */
    @Override
    public OffsetTime getCreatedAt() {
        return (OffsetTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, OffsetTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, OffsetTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbCategory.TB_CATEGORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbCategory.TB_CATEGORY.CID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbCategory.TB_CATEGORY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbCategory.TB_CATEGORY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbCategory.TB_CATEGORY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetTime> field6() {
        return TbCategory.TB_CATEGORY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value2(String value) {
        setCid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord value6(OffsetTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCategoryRecord values(Long value1, String value2, String value3, String value4, String value5, OffsetTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCategory from) {
        setId(from.getId());
        setCid(from.getCid());
        setName(from.getName());
        setDescription(from.getDescription());
        setCreatedBy(from.getCreatedBy());
        setCreatedAt(from.getCreatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCategory> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCategoryRecord
     */
    public TbCategoryRecord() {
        super(TbCategory.TB_CATEGORY);
    }

    /**
     * Create a detached, initialised TbCategoryRecord
     */
    public TbCategoryRecord(Long id, String cid, String name, String description, String createdBy, OffsetTime createdAt) {
        super(TbCategory.TB_CATEGORY);

        set(0, id);
        set(1, cid);
        set(2, name);
        set(3, description);
        set(4, createdBy);
        set(5, createdAt);
    }

    public TbCategoryRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
