/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;

import jooq.tables.TbComment;
import jooq.tables.interfaces.ITbComment;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCommentRecord extends UpdatableRecordImpl<TbCommentRecord> implements VertxPojo, Record10<Long, String, String, String, Integer, String, String, String, String, String>, ITbComment {

    private static final long serialVersionUID = 1813001421;

    /**
     * Setter for <code>public.tb_comment.id</code>.
     */
    @Override
    public TbCommentRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_comment.authorid</code>.
     */
    @Override
    public TbCommentRecord setAuthorid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.authorid</code>.
     */
    @Override
    public String getAuthorid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_comment.cid</code>.
     */
    @Override
    public TbCommentRecord setCid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.cid</code>.
     */
    @Override
    public String getCid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_comment.storyid</code>.
     */
    @Override
    public TbCommentRecord setStoryid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.storyid</code>.
     */
    @Override
    public String getStoryid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_comment.possibilitysensitive</code>.
     */
    @Override
    public TbCommentRecord setPossibilitysensitive(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.possibilitysensitive</code>.
     */
    @Override
    public Integer getPossibilitysensitive() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tb_comment.lang</code>.
     */
    @Override
    public TbCommentRecord setLang(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.lang</code>.
     */
    @Override
    public String getLang() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_comment.entities</code>.
     */
    @Override
    public TbCommentRecord setEntities(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.entities</code>.
     */
    @Override
    public String getEntities() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_comment.authorname</code>.
     */
    @Override
    public TbCommentRecord setAuthorname(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.authorname</code>.
     */
    @Override
    public String getAuthorname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_comment.createdon</code>.
     */
    @Override
    public TbCommentRecord setCreatedon(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.createdon</code>.
     */
    @Override
    public String getCreatedon() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_comment.comment</code>.
     */
    @Override
    public TbCommentRecord setComment(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_comment.comment</code>.
     */
    @Override
    public String getComment() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, Integer, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbComment.TB_COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbComment.TB_COMMENT.AUTHORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbComment.TB_COMMENT.CID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbComment.TB_COMMENT.STORYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TbComment.TB_COMMENT.POSSIBILITYSENSITIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TbComment.TB_COMMENT.LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbComment.TB_COMMENT.ENTITIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TbComment.TB_COMMENT.AUTHORNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbComment.TB_COMMENT.CREATEDON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TbComment.TB_COMMENT.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStoryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPossibilitysensitive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getEntities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAuthorname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStoryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPossibilitysensitive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEntities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAuthorname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value2(String value) {
        setAuthorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value3(String value) {
        setCid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value4(String value) {
        setStoryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value5(Integer value) {
        setPossibilitysensitive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value6(String value) {
        setLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value7(String value) {
        setEntities(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value8(String value) {
        setAuthorname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value9(String value) {
        setCreatedon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord value10(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCommentRecord values(Long value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbComment from) {
        setId(from.getId());
        setAuthorid(from.getAuthorid());
        setCid(from.getCid());
        setStoryid(from.getStoryid());
        setPossibilitysensitive(from.getPossibilitysensitive());
        setLang(from.getLang());
        setEntities(from.getEntities());
        setAuthorname(from.getAuthorname());
        setCreatedon(from.getCreatedon());
        setComment(from.getComment());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbComment> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCommentRecord
     */
    public TbCommentRecord() {
        super(TbComment.TB_COMMENT);
    }

    /**
     * Create a detached, initialised TbCommentRecord
     */
    public TbCommentRecord(Long id, String authorid, String cid, String storyid, Integer possibilitysensitive, String lang, String entities, String authorname, String createdon, String comment) {
        super(TbComment.TB_COMMENT);

        set(0, id);
        set(1, authorid);
        set(2, cid);
        set(3, storyid);
        set(4, possibilitysensitive);
        set(5, lang);
        set(6, entities);
        set(7, authorname);
        set(8, createdon);
        set(9, comment);
    }

    public TbCommentRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
