/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.TbCompany;
import jooq.tables.interfaces.ITbCompany;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCompanyRecord extends UpdatableRecordImpl<TbCompanyRecord> implements VertxPojo, Record16<Long, String, String, String, String, Integer, String, String, String, String, String, OffsetTime, String, String, String, String>, ITbCompany {

    private static final long serialVersionUID = -1329935065;

    /**
     * Setter for <code>public.tb_company.id</code>.
     */
    @Override
    public TbCompanyRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_company.name</code>.
     */
    @Override
    public TbCompanyRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_company.location</code>.
     */
    @Override
    public TbCompanyRecord setLocation(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.location</code>.
     */
    @Override
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_company.phone_number</code>.
     */
    @Override
    public TbCompanyRecord setPhoneNumber(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.phone_number</code>.
     */
    @Override
    public String getPhoneNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_company.sector</code>.
     */
    @Override
    public TbCompanyRecord setSector(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.sector</code>.
     */
    @Override
    public String getSector() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_company.rating</code>.
     */
    @Override
    public TbCompanyRecord setRating(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.rating</code>.
     */
    @Override
    public Integer getRating() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tb_company.logo</code>.
     */
    @Override
    public TbCompanyRecord setLogo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.logo</code>.
     */
    @Override
    public String getLogo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_company.background_info</code>.
     */
    @Override
    public TbCompanyRecord setBackgroundInfo(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.background_info</code>.
     */
    @Override
    public String getBackgroundInfo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_company.pictures</code>.
     */
    @Override
    public TbCompanyRecord setPictures(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.pictures</code>.
     */
    @Override
    public String getPictures() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_company.company_id</code>.
     */
    @Override
    public TbCompanyRecord setCompanyId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.company_id</code>.
     */
    @Override
    public String getCompanyId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tb_company.company_code</code>.
     */
    @Override
    public TbCompanyRecord setCompanyCode(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.company_code</code>.
     */
    @Override
    public String getCompanyCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tb_company.created_at</code>.
     */
    @Override
    public TbCompanyRecord setCreatedAt(OffsetTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.created_at</code>.
     */
    @Override
    public OffsetTime getCreatedAt() {
        return (OffsetTime) get(11);
    }

    /**
     * Setter for <code>public.tb_company.created_by</code>.
     */
    @Override
    public TbCompanyRecord setCreatedBy(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.created_by</code>.
     */
    @Override
    public String getCreatedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tb_company.email</code>.
     */
    @Override
    public TbCompanyRecord setEmail(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.tb_company.website</code>.
     */
    @Override
    public TbCompanyRecord setWebsite(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.website</code>.
     */
    @Override
    public String getWebsite() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tb_company.other_links</code>.
     */
    @Override
    public TbCompanyRecord setOtherLinks(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_company.other_links</code>.
     */
    @Override
    public String getOtherLinks() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, Integer, String, String, String, String, String, OffsetTime, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, Integer, String, String, String, String, String, OffsetTime, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbCompany.TB_COMPANY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbCompany.TB_COMPANY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbCompany.TB_COMPANY.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbCompany.TB_COMPANY.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbCompany.TB_COMPANY.SECTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TbCompany.TB_COMPANY.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbCompany.TB_COMPANY.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TbCompany.TB_COMPANY.BACKGROUND_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbCompany.TB_COMPANY.PICTURES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TbCompany.TB_COMPANY.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TbCompany.TB_COMPANY.COMPANY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetTime> field12() {
        return TbCompany.TB_COMPANY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TbCompany.TB_COMPANY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TbCompany.TB_COMPANY.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TbCompany.TB_COMPANY.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TbCompany.TB_COMPANY.OTHER_LINKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBackgroundInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPictures();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime component12() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getOtherLinks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBackgroundInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPictures();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime value12() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getOtherLinks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value3(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value4(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value5(String value) {
        setSector(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value6(Integer value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value7(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value8(String value) {
        setBackgroundInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value9(String value) {
        setPictures(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value10(String value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value11(String value) {
        setCompanyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value12(OffsetTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value13(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value14(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value15(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord value16(String value) {
        setOtherLinks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCompanyRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10, String value11, OffsetTime value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbCompany from) {
        setId(from.getId());
        setName(from.getName());
        setLocation(from.getLocation());
        setPhoneNumber(from.getPhoneNumber());
        setSector(from.getSector());
        setRating(from.getRating());
        setLogo(from.getLogo());
        setBackgroundInfo(from.getBackgroundInfo());
        setPictures(from.getPictures());
        setCompanyId(from.getCompanyId());
        setCompanyCode(from.getCompanyCode());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setEmail(from.getEmail());
        setWebsite(from.getWebsite());
        setOtherLinks(from.getOtherLinks());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbCompany> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCompanyRecord
     */
    public TbCompanyRecord() {
        super(TbCompany.TB_COMPANY);
    }

    /**
     * Create a detached, initialised TbCompanyRecord
     */
    public TbCompanyRecord(Long id, String name, String location, String phoneNumber, String sector, Integer rating, String logo, String backgroundInfo, String pictures, String companyId, String companyCode, OffsetTime createdAt, String createdBy, String email, String website, String otherLinks) {
        super(TbCompany.TB_COMPANY);

        set(0, id);
        set(1, name);
        set(2, location);
        set(3, phoneNumber);
        set(4, sector);
        set(5, rating);
        set(6, logo);
        set(7, backgroundInfo);
        set(8, pictures);
        set(9, companyId);
        set(10, companyCode);
        set(11, createdAt);
        set(12, createdBy);
        set(13, email);
        set(14, website);
        set(15, otherLinks);
    }

    public TbCompanyRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
